substitutions:
  vendor: ballu
  dev_name: oneair
  model: asp-80
  TK2_mode: false # До 10.25 - true, после false

#ESP32 Определение нужных GPIO
  base: esp32dev
  touch_1: GPIO2                # Кнопка скорость вентилятора
  touch_2: GPIO12               # Кнопка нагреватель
  touch_3: GPIO13               # Кнопка Led-индикация
  led_status: GPIO14            # Светодиод Led-индикация
  led_heating: GPIO15           # Светодиод нагреватель
  led_1_speed: GPIO16           # Светодиод скорость 1
  led_2_speed: GPIO17           # Светодиод скорость 2
  led_3_speed: GPIO18           # Светодиод скорость 3
  buzzer: GPIO19                # Буззер
  fan_fg: GPIO21                # Вентилятор FG
  fan_pwm: GPIO22               # Вентилятор PWM
  fan_pwr: GPIO23               # Вентилятор PWR
  heating: GPIO25               # Нагреватель
  sensor_open: GPIO26           # Сенсоры открытия
  sensor_ntc: GPIO36            # Сенсоры температуры
  led_1_RGB: GPIO4              # RGB 1
  led_2_RGB: GPIO5              # RGB 2
  led_3_RGB: GPIO24             # RGB 3

globals:
  - id: errors
    type: bool
    initial_value: 'false'
  - id: half_led
    type: bool
    initial_value: 'false'
    restore_value: True

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esphome:
  name: ${vendor}-${dev_name}-${model}
  friendly_name: Ballu OneAir ASP-80
  name_add_mac_suffix: true
  on_boot:
    priority: 600
    then:
      - output.turn_on: buzzer  # Звук при включении включаем
      - output.turn_off: heating_gpio
      - output.turn_off: fan_power
      - output.turn_on: led_1_speed
      - output.turn_on: led_2_speed
      - output.turn_on: led_3_speed
      - output.turn_on: led_heating
      - delay: 700ms
      - output.turn_off: led_1_speed
      - output.turn_off: led_2_speed
      - output.turn_off: led_3_speed
      - output.turn_off: led_heating
      - fan.turn_off: fan_output
      - output.turn_off: buzzer   # Звук при включении отключаем
# Автоматические запуск на 1 скорости после включения
#      - lambda: |-
#          id(fan_output).turn_on().set_speed(30).perform();

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
ota:
  - platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${vendor}-${dev_name}-${model}
    password: "12345678"

captive_portal:
web_server:
  local: true

output:
  - platform: gpio
    pin: ${buzzer}
    id: buzzer

  - platform: ledc
    id: id_status_led
    pin:
      number: $led_status
      inverted: True

  - platform: ledc
    pin: ${fan_pwm}
    id: fan_pwm_gpio
    inverted: True
    min_power: 0.22 # Минимальная мощность. при попытке выставить мощность менее 20% турбина не запускается, но если активировать эту строку, то почему-то вообще не работает. Шим тупо не включается.
    max_power: 0.74 # Масксимальная мощность подаваемая на турбину. Больше 74 - нехватает питания для турбины, будет перезагрузка при попытке включить ее на максимум.
    zero_means_zero: True

  - platform: ledc
    pin: ${led_heating}
    id: led_heating
    inverted: True

  - platform: ledc
    pin: ${led_1_speed}
    id: led_1_speed
    inverted: True
  - platform: ledc
    pin: ${led_2_speed}
    id: led_2_speed
    inverted: True
  - platform: ledc
    pin: ${led_3_speed}
    id: led_3_speed
    inverted: True

  - platform: gpio
    pin: ${fan_pwr}
    id: fan_power

  - platform: ledc
    pin: ${heating}
    id: heating_gpio

light:
  - platform: status_led
    id: led_info
    output: id_status_led
    effects: 
      - strobe:
          name: error
          colors:
            - state: true
              duration: 1s
            - state: false
              duration: 1s

script:
  - id: play_beep
    then:
      - if:
          condition:
            switch.is_on: buzzer_enable
          then:
            - output.turn_on: buzzer
            - delay: 700ms
            - output.turn_off: buzzer
  - id: play_beep_short
    then:
      - if:
          condition:
            switch.is_on: buzzer_enable
          then:
            - output.turn_on: buzzer
            - delay: 200ms
            - output.turn_off: buzzer
  - id: play_invalid
    then:
      - output.turn_on: buzzer
      - delay: 50ms
      - output.turn_off: buzzer
      - delay: 50ms
      - output.turn_on: buzzer
      - delay: 50ms
      - output.turn_off: buzzer
      - delay: 50ms
      - output.turn_on: buzzer
      - delay: 50ms
      - output.turn_off: buzzer
  - id: play_error
    then:
      - light.turn_on:
          id: led_info
          effect: error
      - lambda: 'id(errors) = true;'
      - script.execute: play_invalid
      
        
  - id: led_check
    then:
      - if:
          condition:
            switch.is_off: led_enable
          then:
            script.execute: led_off
          else:
          - if:
              condition:
                switch.is_on: heater_output
              then:
                if:
                  condition:
                    lambda: "return id(half_led);"
                  then:
                    output.set_level:
                      id: led_heating
                      level: 15%
                  else:
                    output.set_level:
                      id: led_heating
                      level: 100%
              else: 
                output.turn_off: led_heating
          - lambda: |-
              if (id(fan_output).state) {
                if (id(fan_output).speed >= 30) id(led_1_speed).set_level(id(half_led)?0.15:1);
                else id(led_1_speed).turn_off();
                if (id(fan_output).speed >= 65) id(led_2_speed).set_level(id(half_led)?0.15:1);
                else id(led_2_speed).turn_off();
                if (id(fan_output).speed >= 100) id(led_3_speed).set_level(id(half_led)?0.15:1);
                else id(led_3_speed).turn_off();
              } else {
                id(led_1_speed).turn_off();
                id(led_2_speed).turn_off();
                id(led_3_speed).turn_off();
              }
  - id: led_off
    then:
      - output.turn_off: led_1_speed
      - output.turn_off: led_2_speed
      - output.turn_off: led_3_speed
      - output.turn_off: led_heating
        
  - id: fan_start
    then:
      - if:
          condition:
            binary_sensor.is_on: sensor_open
          then:
            - script.execute: play_error
            - script.execute: fan_stop
          else:
            - script.execute: play_beep_short
            - output.turn_on: fan_power
            - script.execute: led_check
              
  - id: fan_stop
    then:
      - output.turn_off: fan_power
      - if:
          condition:
            switch.is_on: heater_output
          then:
            script.execute: heat_stop
      - script.execute: led_check
  - id: heat_output_change
    then:
      - script.execute: heat_change
      - lambda: 'global_preferences->sync();'
  - id: heat_set_target
    then:
      if:
        condition:
          switch.is_on: heater_output
        then:
          - lambda: |-
              float target =  std::clamp(((id(target_power).state * (id(fan_output).speed / 100.0f)) / 100.0f) * (1.0f + (20.0f - id(temperature).state)/100.0f),0.0f,1.0f);
              id(heating_gpio).set_level(target);
              id(heat_current).publish_state(target * 100.0);
  - id: heat_change
    then:
      - script.execute: led_check             
      - if:
          condition:
            switch.is_on: heater_output
          then:
            script.execute: heat_set_target
          else:
            script.execute: heat_stop
            
  - id: heat_stop
    then: 
      - switch.template.publish:
          id: heater_output
          state: false
      - output.turn_off: heating_gpio
              
interval:
  - interval: 30s
    then:
      - if:
          condition:
            and:
            - fan.is_on: fan_output
            - lambda: 'return id(fan_rpm).state < 1.0;'
          then:
            - delay: 10s
            - if:
                condition:
                  and:
                  - fan.is_on: fan_output
                  - lambda: 'return id(fan_rpm).state < 1.0;'
                then:
                  - script.execute: play_error
                  - script.execute: fan_stop
                  
sensor: 
  - platform: pulse_counter
    pin:
      number: $fan_fg
      mode: INPUT_PULLUP
    name: ${dev_name}_rpm
    id: fan_rpm
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.05
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 3s
    
  - platform: template
    name: ${dev_name}_heat_current
    id: heat_current
    icon: "mdi:thermometer-auto"
    unit_of_measurement: '%'
    update_interval: never

  - platform: resistance
    id: resistance_ntc_sensor
    sensor: source_ntc_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm
    reference_voltage:  3.3V
  - platform: adc
    id: source_ntc_sensor
    pin: ${sensor_ntc}
    update_interval: 10s
    attenuation: auto
  - platform: ntc
    name: ${dev_name}_temperature
    id: temperature
    sensor: resistance_ntc_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 20°C
      reference_resistance: 12.5kOhm
    on_value:
      script.execute: heat_set_target

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${dev_name}_ip
      icon: "mdi:lan"
    ssid:
      name: ${dev_name}_ssid
      icon: "mdi:wifi"
    mac_address:
      name: ${dev_name}_mac
      icon: "mdi:lan"

binary_sensor:
  - platform: gpio
    id: sensor_open
    name: ${dev_name}_open
    icon: "mdi:fan-alert"
    use_interrupt: false
    pin:
      number: $sensor_open
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      if:
        condition:
          fan.is_on: fan_output
        then:
          - script.execute: play_error
          - fan.turn_off: fan_output
        else:
          - script.execute: play_beep
          - light.turn_off: led_info
          - lambda: 'id(errors) = false;'
    on_release: 
      - script.execute: play_beep
      - light.turn_off: led_info
      - lambda: 'id(errors) = false;'       

  - platform: gpio
    pin: 
      number: ${touch_1}
      inverted: True
    id: touch_1
    use_interrupt: false
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_multi_click:
      - timing:
          - ON for at least 2s
        then:
          - script.execute: play_beep
          - fan.turn_off: fan_output
    on_press:
      then:
        if:
          condition:
            fan.is_on: fan_output
          then:
            - script.execute: play_beep_short
            - lambda: |-
                if (id(fan_output).speed < 30) id(fan_output).turn_on().set_speed(30).perform();
                else if (id(fan_output).speed < 65) id(fan_output).turn_on().set_speed(65).perform();
                else if (id(fan_output).speed < 100) id(fan_output).turn_on().set_speed(100).perform();
                else id(fan_output).turn_on().set_speed(30).perform();
            - script.execute: led_check
          else:
            fan.turn_on: fan_output
            
  - platform: gpio
    pin: 
      number: ${touch_2}
      inverted: ${TK2_mode}
    id: touch_2
    use_interrupt: false
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          if:
            condition:
              switch.is_off: heater_output
            then:
              switch.turn_on: heater_output
    on_press:
      then:
        if:
          condition:
            switch.is_on: heater_output
          then:
            switch.turn_off: heater_output

  - platform: gpio
    pin: 
      number: ${touch_3}
      inverted: True
    id: touch_3
    use_interrupt: false
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_multi_click:
      - timing:
          - ON for at least 10s
        then:
          - output.turn_on: buzzer
          - output.turn_on: led_1_speed
          - output.turn_on: led_2_speed
          - output.turn_on: led_3_speed
          - output.turn_on: led_heating
          - delay: 50ms
          - output.turn_off: buzzer
          - output.turn_off: led_1_speed
          - output.turn_off: led_2_speed
          - output.turn_off: led_3_speed
          - output.turn_off: led_heating
          - delay: 50ms
          - output.turn_on: buzzer
          - output.turn_on: led_1_speed
          - output.turn_on: led_2_speed
          - output.turn_on: led_3_speed
          - output.turn_on: led_heating
          - delay: 50ms
          - output.turn_off: buzzer
          - output.turn_off: led_1_speed
          - output.turn_off: led_2_speed
          - output.turn_off: led_3_speed
          - output.turn_off: led_heating
          - delay: 50ms
          - output.turn_on: buzzer
          - output.turn_on: led_1_speed
          - output.turn_on: led_2_speed
          - output.turn_on: led_3_speed
          - output.turn_on: led_heating
          - delay: 50ms
          - output.turn_off: buzzer
          - output.turn_off: led_1_speed
          - output.turn_off: led_2_speed
          - output.turn_off: led_3_speed
          - output.turn_off: led_heating
          - lambda: |-
              ESP_LOGW("DMF", "Erase settings and restart...");
              wifi::global_wifi_component->save_wifi_sta("-----", "");
              delay(500);
              esp_restart();
    on_press:
      then:
        - script.execute: play_beep_short
        - if:
            condition:
              lambda: "return id(errors);"
            then:
              - light.turn_off: led_info
              - lambda: "id(errors) = false;"
            else:
              - if:
                  condition:
                    switch.is_off: led_enable
                  then:
                    - lambda: "id(half_led) = true;"
                    - switch.turn_on: led_enable
                  else: 
                    - if:
                        condition:
                            lambda: "return id(half_led);"
                        then:
                          - lambda: "id(half_led) = false;"
                          - script.execute: led_check
                        else:
                          switch.turn_off: led_enable

fan:
  - platform: speed
    output: fan_pwm_gpio
    id: fan_output
    name: ${dev_name}_fan
    on_state:
      script.execute: heat_change
    on_turn_on: 
      script.execute: fan_start
    on_turn_off:
      script.execute: fan_stop

number:
  - platform: template
    name: ${dev_name}_heat_power
    optimistic: true
    min_value: 10.0
    max_value: 100.0
    step: 5.0
    restore_value: true
    id: target_power
    icon: "mdi:thermometer-lines"
    unit_of_measurement: "%"
    on_value:
      script.execute: heat_output_change

switch:
  - platform: template
    id: heater_output
    name: ${dev_name}_heat
    icon: "mdi:heat-wave"
    turn_on_action:    
      if:
        condition:
          fan.is_on: fan_output
        then:
          - switch.template.publish:
              id: heater_output
              state: true
          - script.execute: play_beep_short
          - script.execute: heat_change
        else:
          - script.execute: play_invalid
          - script.execute: heat_stop
    turn_off_action:
      - script.execute: play_beep_short
      - script.execute: heat_stop

  - platform: template
    id: led_enable
    name: ${dev_name}_led
    icon: "mdi:lightbulb-on"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: "config"
    on_turn_on:
      script.execute: led_check
    on_turn_off: 
      script.execute: led_off
  
  - platform: template
    id: buzzer_enable
    name: ${dev_name}_buzzer
    icon: "mdi:volume-high"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: "config"

button:
  - platform: safe_mode
    name: ${dev_name}_safe_mode
